### ISSUE TITLE
Minor attachment display glitches

### ISSUE THREAD

**Issue by philip-iii** [mronkko/ZotPad#33]
I finally got to test the latest beta. Apart from one crash and one item list freeze, both of which I have yet to reproduce, I observed the following minor display glitch when loading attachments (using WebDAV):

When I select an item (not selected previously), the white box where the attachments are displayed expands as usual, but remains blank/white and the attachments are not shown, no matter how long I wait:
![Before](http://dl.dropbox.com/u/26354242/photo%281%29.PNG) "Before")

When I select another item and then select the item in question again, the attachments are shown:
![After](http://dl.dropbox.com/u/26354242/photo%282%29.PNG)

Note that this is not always the case, as some attachments are shown straight away as the white box expands. It is potentially caused by a race condition.

I don't know if this is WebDAV specific, as I cannot test Dropbox and Zotero Storage at the moment.

Other than that, it is really snappy so far.

**Comment by mronkko** [comment]
This is not webdav specific, and is something that I think I fixed in around build number 5.

Can you get this to happen with the most recent build (9) ?

**Comment by mronkko** [comment]
The latest build is actually number 8, not 9.

**Comment by philip-iii** [comment]
I am running build # 6 at the moment (the last one I got an e-mail invitation for. I see now that build # 8 is already available. It just occurred once at the very beginning with the new build, while items were still being downloaded. I suspect that may have had something to do with setting up WebDAV only after some items were downloaded in the previous build (the attachment icons were also missing in the list for items that were not previously selected). 

As such, I would consider this resolved in the latest build.

**Comment by mronkko** [comment]
I just realized what this issue is and it is not fixed. The file icons that are included in zotpad are scalable vector graphics that need to be rendered. Once a file is rendered once, it is saved as a normal png image file. The rendering process is quite complicated due to limitations in iOS, and this bug is a symptom of a bug in that process.

**Comment by philip-iii** [comment]
OK, I will keep that in mind, but so far I have not been able to reproduce this with the latest build. As far as rendering SVGs, I assume you also render the page previews, which is the complicated part, but which is also done on demand once a file is downloaded. As far as the icons are concerned (e.g. generic PDF, HTML, etc. icons), I guess these can either be pre-rendered (as they are static) or rendered once and then referenced in all other instances, but maybe I am missing something.

**Comment by mronkko** [comment]
The icons are rendered once and then stored in cache. I am not distributing prerendered icons because 8 difference sizes would be needed for each icon to support all possible devices. I might distibute some (e.g. PDF, webpage) as prerendered in the final version.

Rendering the SVG files and page previews are done differently. Due to limitations in iOS, the SVG files are basically loaded in embedded webbrowser (UIWebView) and then I take a screenshot of that. 

But in any case, in the worst case, failure in this process should only result in a blank file type icon, not missing document s in the carousel. 

I am reopening this so that I remember to do some testing of this later on.

**Comment by mronkko** [comment]
Does not happen any more
